# BabyTankSwitcher.spec
# PyInstaller spec — run with:  pyinstaller BabyTankSwitcher.spec

import sys
from pathlib import Path
import customtkinter

block_cipher = None

# ── Locate the customtkinter data files (themes, fonts, images) ───────────────
ctk_path = Path(customtkinter.__file__).parent

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        # Bundle the entire customtkinter package so themes/fonts work
        (str(ctk_path), 'customtkinter'),
    ],
    hiddenimports=[
        # tkinter internals PyInstaller sometimes misses
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.colorchooser',
        # PIL / Pillow
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageGrab',
        'PIL.ImageDraw',
        # Win32 / pywin32
        'win32gui',
        'win32con',
        'win32ui',
        'win32process',
        'win32api',
        'pywintypes',
        'winerror',
        # psutil
        'psutil',
        'psutil._pswindows',
        # customtkinter internals
        'customtkinter.windows',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.core_rendering',
        'customtkinter.windows.widgets.theme',
        'customtkinter.windows.widgets.font',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Things we definitely don't need — shrinks the exe
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'gi',
        'IPython',
        'jupyter',
        'notebook',
        'email',
        'html',
        'http',
        'urllib',
        'xml',
        'xmlrpc',
        'pydoc',
        'doctest',
        'unittest',
        'difflib',
        'sqlite3',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BabyTankSwitcher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,           # compress with UPX if available (smaller exe)
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,      # no console window — windowed app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='assets/icon.ico',   # uncomment and add icon.ico to use a custom icon
    version='version_info.txt',  # Windows version metadata (generated by workflow)
)
